# Generated by Django 3.1.6 on 2021-09-24 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('step', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('nameOrig', models.CharField(blank=True, max_length=255, null=True)),
                ('oldbalanceOrig', models.CharField(blank=True, max_length=255, null=True)),
                ('newbalanceOrig', models.CharField(blank=True, max_length=255, null=True)),
                ('nameDest', models.CharField(blank=True, max_length=255, null=True)),
                ('oldbalanceDest', models.CharField(blank=True, max_length=255, null=True)),
                ('newbalanceDest', models.CharField(blank=True, max_length=255, null=True)),
                ('isFraud', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
